site_name: flex-config
site_description: Configure Python apps easily
site_url: https://triaxtec.github.io/flex-config

theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'green'
    icon:
        repo: fontawesome/brands/github-alt

repo_name: triaxtec/flex-config
repo_url: https://github.com/triaxtec/flex-config
edit_uri: ''

nav:
    - Intro: 'README.md'
    - Tutorial: 'tutorial.md'
    - Changelog: 'CHANGELOG.md'
    - API:
        construct_config: construct_config.md
    - "Config Sources":
        ConfigSource: ConfigSources/config_source.md
        EnvSource: ConfigSources/env_source.md
        AWSSource: ConfigSources/aws_source.md
        JSONSource: ConfigSources/FileSources/json_source.md
        TOMLSource: ConfigSources/FileSources/toml_source.md
        YAMLSource: ConfigSources/FileSources/yaml_source.md

markdown_extensions:
    - toc:
        permalink: true
    - markdown_include.include:
        base_path: docs
    - admonition
    - codehilite:
        linenums: true
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    filters:
                        - "!^__"
                rendering:
                    show_source: true
                    show_root_full_path: false
        watch:
            - flex_config

