version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages


jobs:
  test:
    docker:
    - image: circleci/python:3.8
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "poetry.lock" }}
    - run:
        name: Install Dependencies
        command: |
          pip install poetry --user --upgrade
          poetry config virtualenvs.in-project true
          poetry install -E all

    - run:
        name: Run Tests
        command: |
          mkdir -p test-reports/safety test-reports/mypy test-reports/pytest
          poetry run black . --check
          poetry run isort
          poetry run safety check --json > test-reports/safety/results.json
          poetry run mypy flex_config --junit-xml=test-reports/mypy/results.xml
          poetry run pytest --junitxml=test-reports/pytest/results.xml --cov=flex_config
          poetry run coverage xml
    - store_test_results:
        path: test-reports
    - codecov/upload:
        file: coverage.xml
    - run:
        command: poetry run pip uninstall flex-config -y
        name: Uninstall Package
    - save_cache:
        key: v1-dependencies-{{ checksum "poetry.lock" }}
        paths:
        - ./.venv
    working_directory: ~/repo
