name: Run Checks and Tests

# Cancels previous runs of this workflow in this branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - 'develop'
    # Tags don't need to be tested a second time
    tags-ignore:
      - '**'

jobs:
  run-checks-and-test:
    name: Run Checks and Tests
    uses: triaxtec/github-actions/.github/workflows/python-run-checks-and-tests.yml@v3
    with:
      module: flex_config
      start-services-with-docker-compose: false
      python-version: "3.10"
